const allWords = [
  { word: "Accusation", definition: "claim that someone has done something wrong" },
  { word: "Acolyte", definition: "devoted follower" },
  
  { word: "Bureaucracy", definition: "administrative system with many rules" },
  { word: "Coalition", definition: "temporary alliance for combined action" },
  { word: "Consensus", definition: "general agreement" },
  { word: "Dissent", definition: "disagreement with commonly held views" },
  { word: "Legislature", definition: "law-making body" },
  
  { word: "Referendum", definition: "general vote by the electorate" },
  
  { word: "Beneficiary", definition: "recipient of benefits" },
  { word: "Bipartisan", definition: "supported by two political parties" },
  { word: "Constituency", definition: "area served by an elected official" },
  { word: "Deferment", definition: "postponement" },
 
  { word: "Filibuster", definition: "delaying tactic used in legislative debate" },
  { word: "Hierarchy", definition: "system ranking people or groups" },
  
  { word: "Impeachment", definition: "process of charging public official" },
  { word: "Inaugurate", definition: "begin or introduce" },
 
  
  { word: "Sovereignty", definition: "supreme power or authority" },
  { word: "Subpoena", definition: "writ ordering someone to attend court" },
  { word: "Surveillance", definition: "close observation" },
  
  { word: "Corroborate", definition: "confirm or give support to a statement" },
  { word: "Disenfranchise", definition: "deprive someone of the right to vote" },
  { word: "Expedite", definition: "make something happen sooner" },
  { word: "Insurrection", definition: "violent uprising against authority" },
 
  { word: "Manifesto", definition: "public declaration of policy and aims" },
  { word: "Obfuscate", definition: "deliberately make something unclear" },

  { word: "Plagiarize", definition: "take someone else's work as one's own" },
 
  { word: "Stalemate", definition: "situation with no possible progress" },
  { word: "Totalitarian", definition: "centralized and dictatorial government" },
 
  { word: "Allegation", definition: "claim of wrongdoing" },
 
 
  { word: "Ascertain", definition: "find out for certain" },
  { word: "Belligerent", definition: "hostile and aggressive" },
  { word: "Capitulate", definition: "surrender" },
  { word: "Censure", definition: "express severe disapproval" },
  { word: "Coercion", definition: "use of force or threats" },
  { word: "Collusion", definition: "secret cooperation for deceitful purposes" },
  
  { word: "Contravene", definition: "violate a law or rule" },
 
  { word: "Disparate", definition: "fundamentally different or distinct" },
  { word: "Disseminate", definition: "spread widely" },
 
  { word: "Echelon", definition: "rank in an organization" },
  { word: "Egalitarian", definition: "promoting equal rights" },
  { word: "Elucidate", definition: "make clear; explain" },
  { word: "Embezzlement", definition: "theft of funds" },
  { word: "Endeavor", definition: "try hard to achieve something" },
  { word: "Endorsement", definition: "public support" },
  { word: "Ephemeral", definition: "lasting a very short time" },
  { word: "Esoteric", definition: "intended for or understood by a small group" },
  { word: "Evanescent", definition: "fading away quickly" },
  { word: "Exacerbate", definition: "worsen" },
  { word: "Facsimile", definition: "exact copy" },
  { word: "Flagrant", definition: "obviously offensive" },
  { word: "Galvanize", definition: "shock into action" },
  { word: "Gerrymander", definition: "manipulate boundaries for advantage" },
  { word: "Harangue", definition: "lengthy and aggressive speech" },
  { word: "Hegemony", definition: "dominance by one group over others" },
  { word: "Incontrovertible", definition: "not able to be denied or disputed" },
  { word: "Ineffable", definition: "too great or extreme to be expressed" },
  { word: "Irrefutable", definition: "impossible to deny or disprove" },
  { word: "Juxtapose", definition: "place side by side for comparison" },
  { word: "Magnanimous", definition: "generous" },
  { word: "Malfeasance", definition: "wrongdoing by public official" },
  { word: "Omnipotent", definition: "having unlimited power" },
  { word: "Philanthropy", definition: "desire to promote the welfare of others" },
  { word: "Pseudonym", definition: "false name" },
  { word: "Rescind", definition: "revoke or cancel" },
  { word: "Sacrosanct", definition: "sacred; not to be interfered with" },
  { word: "Discrimination", definition: "unfair treatment based on group membership" },
  { word: "Marginalize", definition: "treat as insignificant or peripheral" },
  { word: "Persecution", definition: "cruel treatment due to race, religion, politics" },
  { word: "Inequality", definition: "lack of fairness or justice in opportunity" },
  { word: "Prejudice", definition: "preconceived opinion not based on reason" },
  { word: "Stigmatize", definition: "describe or regard as worthy of disgrace" },
  { word: "Segregation", definition: "enforced separation of groups" },
  { word: "Destitution", definition: "severe poverty; lack of resources" },
  { word: "Xenophobia", definition: "intense dislike or fear of foreigners" },
  { word: "Exploitation", definition: "treating someone unfairly for benefit" },
  { word: "Proliferation", definition: "rapid increase in numbers or spread" },
  { word: "Incarceration", definition: "being imprisoned or confined" },
  { word: "Deterioration", definition: "process of becoming progressively worse" },
  { word: "Gentrification", definition: "process of renovating a district resulting in displacement" },
  { word: "Disenfranchise", definition: "deprive of the right to vote" },
  { word: "Reconciliation", definition: "restoration of friendly relations" },
  { word: "Vulnerable", definition: "exposed to possibility of being harmed" },
  { word: "Advocacy", definition: "public support for a cause or policy" },
  { word: "Remediate", definition: "correct or improve a problem" },
  { word: "Perpetrate", definition: "carry out or commit an act (usually crime)" },
  { word: "Solidarity", definition: "unity or agreement in support of a cause" },
  { word: "Ameliorate", definition: "make a situation better or less severe" },
  { word: "Ostracize", definition: "exclude from a group or society" },
  { word: "Disparity", definition: "great difference, especially in social status" },
  { word: "Rehabilitation", definition: "restoration to normal life or functioning" },
  { word: "Intolerance", definition: "unwillingness to accept views of others" },
  { word: "Affirmative", definition: "supporting a policy of inclusion for disadvantaged groups" },
  { word: "Incidence", definition: "rate or occurrence of something (often negative)" },
  { word: "Underprivileged", definition: "lacking basic social and economic benefits" },
  { word: "Dehumanize", definition: "deprive of positive human qualities" },
  { word: "Multilateral", definition: "agreed upon or participated by several parties" },
  { word: "Whistleblower", definition: "person exposing wrongdoing within an organization" },
  { word: "Bureaucratic", definition: "relating to complicated organizational procedures" },
  { word: "Prohibition", definition: "act of forbidding something by law" },
  { word: "Recidivism", definition: "tendency of convicted criminals to reoffend" },
  { word: "Malnutrition", definition: "lack of proper nutrition" },
  { word: "Legitimacy", definition: "lawful, proper, or accepted status" },
  { word: "Displacement", definition: "forced movement from home or origin" },
  { word: "Neoliberal", definition: "favoring free-market capitalism" },
  { word: "Disposition", definition: "natural tendency, attitude, or mood" },
  { word: "Unprecedented", definition: "never done or known before" },
  { word: "Ostracism", definition: "exclusion from a group; social rejection" },
  { word: "Allocation", definition: "distribution of resources or duties" },
  { word: "Infringement", definition: "action breaking limits set by law or rights" },
  { word: "Destitute", definition: "extremely poor and lacking means" },
  { word: "Exacerbate", definition: "make a problem worse" },
  { word: "Disproportionate", definition: "out of proportion; unequal" },
  { word: "Pluralistic", definition: "containing several ethnic, cultural, or religious groups" },
  { word: "Homogeneity", definition: "state of being all the same or similar" },
  { word: "Institutionalize", definition: "establish as practice or norm within an organization" },
  { word: "Impoverished", definition: "made poor; deprived of strength or vitality" },
  { word: "Perpetuate", definition: "make something continue indefinitely" },
  { word: "Polarization", definition: "division into two sharply contrasting groups" },
  { word: "Disillusionment", definition: "disappointment from discovering something is false" },
  { word: "Inequitable", definition: "unfair; not just or equal" },
  { word: "Subsistence", definition: "supporting oneself at minimal level" },
  { word: "Anonymity", definition: "state of being unnamed, unidentified" },
  { word: "Inordinate", definition: "unusually large; excessive" },
  { word: "Assimilate", definition: "absorb or integrate into a wider society" },
  { word: "Volatility", definition: "tendency to change rapidly and unpredictably" },
  { word: "Incursion", definition: "sudden attack or invasion" },
  { word: "Restitution", definition: "returning something lost; compensation" },
  { word: "Indigent", definition: "poor; needy" },
  { word: "Dispossess", definition: "deprive of land, property, or other possessions" },
  { word: "Conscientious", definition: "wishing to do what is right" },
  { word: "Acquiesce", definition: "accept reluctantly but without protest" },
  { word: "Precarious", definition: "not securely held or in position" },
  { word: "Disenchantment", definition: "loss of hope or disappointment" },
  { word: "Stagnation", definition: "lack of movement or progress" },
  { word: "Alienation", definition: "feeling isolated from a group or society" },
  { word: "Advocacy", definition: "speaking or acting in support of a cause" },
  { word: "Diminutive", definition: "extremely small" },
  { word: "Prevalence", definition: "widespread presence of something" },
  { word: "Ostracism", definition: "exclusion from a group" },
  { word: "Perjury", definition: "lying under oath" },
  { word: "Collusion", definition: "secret illegal cooperation" },
  { word: "Subjugate", definition: "bring under domination; conquer" },
  { word: "Mitigate", definition: "make less severe or painful" },
  { word: "Equanimity", definition: "calmness and composure under stress" },
  { word: "Dichotomy", definition: "division into two contrasting parts" },
  { word: "Nihilism", definition: "rejection of all religious and moral principles" },
  { word: "Parity", definition: "state or condition of being equal" },
  { word: "Reciprocity", definition: "practice of exchanging things for mutual benefit" },
  { word: "Stymie", definition: "prevent or hinder progress" },
  { word: "Paradoxical", definition: "seemingly self-contradictory" },
  { word: "Demographic", definition: "relating to structure of populations" },
  { word: "Dispel", definition: "make a feeling, doubt, or belief disappear" },
  { word: "Efficacy", definition: "ability to produce desired outcome" },
  { word: "Inculcate", definition: "instill an idea by persistent instruction" },
  { word: "Culpability", definition: "responsibility for a fault or wrong" },
  { word: "Ephemeral", definition: "lasting for a very short time" },
  { word: "Antithesis", definition: "direct opposite" },
  { word: "Intransigent", definition: "unwilling to change one's views" },
  { word: "Relegate", definition: "assign to a lower position" },
  { word: "Dichotomous", definition: "divided into two parts" },
  { word: "Insidious", definition: "proceeding in a gradual, subtle way with harmful effects" },
  { word: "Idiosyncratic", definition: "relating to peculiar or individual characteristics" },
  { word: "Contentious", definition: "causing or likely to cause argument" },
  { word: "Recalcitrant", definition: "resisting authority; uncooperative" },
  { word: "Disparage", definition: "speak of in a disrespectful manner" },
  { word: "Acquiesce", definition: "accept something reluctantly but without protest" },
  { word: "Anomaly", definition: "something unusual or unexpected" },
  { word: "Astute", definition: "having sharp judgment or insight" },
  { word: "Behemoth", definition: "something very large and powerful" },
  { word: "Belligerent", definition: "hostile and aggressive" },
  { word: "Benevolent", definition: "well-meaning and kind" },
  { word: "Bewilderment", definition: "state of being confused" },
  { word: "Bureaucracy", definition: "system of government or management with many complex rules" },
  { word: "Cacophony", definition: "harsh, discordant mixture of sounds" },
  { word: "Capitulate", definition: "cease to resist; surrender" },
  { word: "Censure", definition: "express severe disapproval" },
  { word: "Charismatic", definition: "exercising a compelling charm" },
  { word: "Clemency", definition: "mercy or lenience" },
  { word: "Coercion", definition: "use of force or threats" },
  { word: "Cogent", definition: "clear, logical, and convincing" },
  { word: "Connoisseur", definition: "an expert, especially in matters of taste" },
  { word: "Conspicuous", definition: "easily seen or noticed" },
  { word: "Conundrum", definition: "a difficult problem; a puzzle" },
  { word: "Credibility", definition: "quality of being trusted and believed" },
  { word: "Deference", definition: "humble submission and respect" },
  { word: "Detrimental", definition: "causing harm or damage" },
  { word: "Dichotomy", definition: "division into two opposing parts" },
  { word: "Disingenuous", definition: "insincere, dishonest" },
  { word: "Disseminate", definition: "spread or disperse widely" },
  { word: "Dissuade", definition: "persuade not to do something" },
  { word: "Egregious", definition: "outstandingly bad; shocking" },
  { word: "Elucidate", definition: "make something clear" },
  { word: "Embellish", definition: "decorate or add details" },
  { word: "Emphatic", definition: "showing or giving emphasis" },
  { word: "Enigmatic", definition: "mysterious or difficult to understand" },
  { word: "Entitlement", definition: "belief one is inherently deserving of privileges" },
  { word: "Ephemeral", definition: "lasting a short time" },
  { word: "Equanimity", definition: "mental calmness, especially in a crisis" },
  { word: "Esoteric", definition: "understood by a select few" },
  { word: "Euphemism", definition: "mild word substitution for something harsh" },
  { word: "Exemplary", definition: "serving as a desirable example" },
  { word: "Exonerate", definition: "clear from blame or fault" },
  { word: "Fallacious", definition: "based on a mistaken belief" },
  { word: "Fastidious", definition: "very attentive to detail" },
  { word: "Flabbergasted", definition: "extremely surprised or shocked" },
  { word: "Fortuitous", definition: "happening by chance and in a good way" },
  { word: "Gregarious", definition: "fond of company; sociable" },
  { word: "Hypocrisy", definition: "pretending to have virtues one does not possess" },
  { word: "Idiosyncrasy", definition: "odd habit or characteristic" },
  { word: "Illicit", definition: "forbidden by law or rules" },
  { word: "Impetuous", definition: "acting quickly without thought or care" },
  { word: "Implicit", definition: "implied, not directly stated" },
  { word: "Impunity", definition: "exemption from punishment" },
  { word: "Incendiary", definition: "causing or stirring up conflict" },
  { word: "Incontrovertible", definition: "not able to be denied" },
  { word: "Indictment", definition: "formal charge or accusation" },
  { word: "Ineffable", definition: "too great or extreme to be described in words" },
  { word: "Ineptitude", definition: "lack of skill or competence" },
  { word: "Ingenuous", definition: "innocent and unsuspecting" },
  { word: "Innuendo", definition: "indirect or subtle reference, often negative" },
  { word: "Insidious", definition: "proceeding subtly but with harmful effects" },
  { word: "Insinuate", definition: "suggest or hint in an indirect way" },
  { word: "Integrity", definition: "quality of being honest and having strong principles" },
  { word: "Interminable", definition: "endless or seeming endless" },
  { word: "Irrefutable", definition: "impossible to deny or disprove" },
  { word: "Juxtapose", definition: "place side by side for contrast" },
  { word: "Languish", definition: "become weak or lose vitality" },
  { word: "Magnanimous", definition: "generous and forgiving" },
  { word: "Malevolent", definition: "having or showing a wish to do evil" },
  { word: "Malfeasance", definition: "wrongdoing by a public official" },
  { word: "Mitigate", definition: "make less severe or harsh" },
  { word: "Nonplussed", definition: "puzzled or unsure how to respond" },
  { word: "Obfuscate", definition: "deliberately make unclear or confusing" },
  { word: "Obsequious", definition: "excessively obedient or attentive" },
  { word: "Ostensible", definition: "stated or appearing to be true, but not necessarily so" },
  { word: "Paradigm", definition: "a typical example or model" },
  { word: "Pejorative", definition: "expressing contempt or disapproval" },
  { word: "Perfunctory", definition: "carried out with minimal effort or reflection" },
  { word: "Pernicious", definition: "having a harmful effect, especially in a gradual way" },
  { word: "Perspicacious", definition: "having a ready insight into and understanding of things" },
  { word: "Philanthropy", definition: "desire to promote the welfare of others" },
  { word: "Placate", definition: "make someone less angry or hostile" },
  { word: "Precocious", definition: "unusually advanced at an early age" },
  { word: "Predilection", definition: "preference or liking for something" },
  { word: "Proclivity", definition: "tendency to choose or do something regularly" },
  { word: "Prodigious", definition: "remarkably large or impressive" },
  { word: "Proliferate", definition: "increase rapidly in number" },
  { word: "Propensity", definition: "inclination or tendency" },
  { word: "Prosaic", definition: "lacking poetic beauty; dull" },
  { word: "Pseudonym", definition: "false or fictitious name" },
  { word: "Quandary", definition: "state of uncertainty over what to do" },
  { word: "Quixotic", definition: "exceedingly idealistic; unrealistic and impractical" },
  { word: "Recalcitrant", definition: "stubbornly disobedient" },
  { word: "Redundant", definition: "not needed; superfluous" },
  { word: "Rescind", definition: "revoke or cancel" },
  { word: "Sagacious", definition: "having good judgment; wise" },
  { word: "Scrupulous", definition: "extremely attentive to detail or ethics" },
  { word: "Serendipity", definition: "occurrence of events by chance in a happy way" },
  { word: "Soliloquy", definition: "act of speaking one's thoughts aloud" },
  { word: "Sycophant", definition: "person who flatters for advantage" },
  { word: "Tangential", definition: "only slightly related to the main point" },
  { word: "Trepidation", definition: "a feeling of fear about something that may happen" },
  { word: "Unprecedented", definition: "never done or known before" },
  { word: "Ubiquitous", definition: "present, appearing, or found everywhere" },
  { word: "Vacillate", definition: "waver between different opinions or actions" },
  { word: "Vehement", definition: "showing strong feeling; forceful, passionate" },
  { word: "Vindicate", definition: "clear from blame or suspicion" },
  { word: "Diplomacy", definition: "managing international relations through negotiation" },
  { word: "Sanctions", definition: "penalties imposed to influence a country's actions" },
  { word: "Sovereignty", definition: "supreme power or authority over a territory" },
  { word: "Bilateral", definition: "involving two parties or countries" },
  { word: "Multilateral", definition: "involving multiple countries or parties" },
  { word: "Arbitration", definition: "official settlement of a dispute by an impartial party" },
  { word: "Embargo", definition: "official ban on trade with a particular country" },
  { word: "Detente", definition: "easing of hostility or strained relations" },
  { word: "Hegemony", definition: "dominance of one state or group over others" },
  { word: "Annexation", definition: "formal act of acquiring territory by a state" },
  { word: "Insurgency", definition: "rising in active revolt against authority" },
  { word: "Coup d'état", definition: "sudden overthrow of a government" },
  { word: "Refugee", definition: "person forced to flee their country due to danger" },
  { word: "Asylum", definition: "protection granted to refugees from danger" },
  { word: "Genocide", definition: "deliberate killing of a large group, especially ethnic" },
  { word: "Diplomate", definition: "skilled in diplomacy (diplomat)" },
  { word: "Treaty", definition: "formal agreement between countries" },
  { word: "Protocol", definition: "official procedure or system of rules" },
  { word: "Mediation", definition: "intervention to resolve conflicts peacefully" },
  { word: "Extradition", definition: "surrendering a person accused of crimes to another jurisdiction" },
  { word: "Expatriate", definition: "person living outside their native country" },
  { word: "Embassies", definition: "diplomatic missions representing a country abroad" },
  { word: "Consulate", definition: "office of a government in a foreign city" },
  { word: "Proxy war", definition: "conflict where opposing powers support other parties" },
  { word: "Realpolitik", definition: "politics based on practical rather than ethical considerations" },
  { word: "Mandate", definition: "authorization to act on behalf of others or for a country" },
  { word: "Insurrection", definition: "violent uprising against authority" },
  { word: "Diaspora", definition: "dispersion of people from their homeland" },
  { word: "Neutrality", definition: "policy of not taking sides in a conflict" },
  { word: "Summit", definition: "meeting of heads of state or government" },
  { word: "Demilitarized", definition: "area where military forces are prohibited" },
  { word: "Reconnaissance", definition: "military observation to gather information" },
  { word: "Conscription", definition: "compulsory enlistment for military service" },
  { word: "Belligerent", definition: "engaged in conflict or war" },
  { word: "Embargoes", definition: "bans on trade with certain nations" },
  { word: "War crimes", definition: "serious violations of laws during war" },
  { word: "Ceasefire", definition: "temporary stoppage of fighting" },
  { word: "Quarantine", definition: "restriction of movement to prevent disease spread" },
  { word: "Diplomats", definition: "officials representing a country abroad" },
  { word: "Espionage", definition: "spying to obtain secret information" },
  { word: "Reparation", definition: "compensation for war damage" },
  { word: "Exile", definition: "forced removal from one's country" },
  { word: "Ballistic", definition: "relating to the motion of projectiles" },
  { word: "Genocide", definition: "systematic destruction of a group" },
  { word: "Hostilities", definition: "acts of warfare" },
  { word: "Insurgent", definition: "participant in an uprising" },
  { word: "Militarization", definition: "process of equipping for war" },
  { word: "Multinational", definition: "involving several countries" },
  { word: "Nonproliferation", definition: "prevention of spread of weapons" },
  { word: "Occupation", definition: "control of territory by military forces" },
  { word: "Pariah", definition: "outcast or socially rejected person or country" },
  { word: "Partition", definition: "division of a country into parts" },
  { word: "Proxy", definition: "substitute authorized to act for another" },
  { word: "Reconciliation", definition: "restoration of friendly relations" },
  { word: "Regime", definition: "government, especially authoritarian" },
  { word: "Resurgence", definition: "rising again to prominence or activity" },
  { word: "Sanctuary", definition: "place offering protection" },
  { word: "Sanctions", definition: "penalties to enforce international law" },
  { word: "Secession", definition: "withdrawal from a political entity" },
  { word: "Sovereignty", definition: "supreme power over a territory" },
  { word: "Suppression", definition: "forceful stopping of something" },
  { word: "Treaty", definition: "formal international agreement" },
  { word: "Truce", definition: "agreement to stop fighting temporarily" },
  { word: "Ultimatum", definition: "final demand before action" },
  { word: "Unilateral", definition: "one-sided action or decision" },
  { word: "Bloc", definition: "group of countries with a common purpose" },
  { word: "Boycott", definition: "refusal to buy or participate" },
  { word: "Ceasefire", definition: "temporary stoppage of hostilities" },
  { word: "Coalition", definition: "alliance for combined action" },
  { word: "Détente", definition: "relaxation of tensions between countries" },
  { word: "Exile", definition: "forced absence from one's country" },
  { word: "Embargo", definition: "prohibition on trade with a country" },
  { word: "Espionage", definition: "spying for government information" },
  { word: "Insurgency", definition: "uprising against government authority" },
  { word: "Mediation", definition: "intervention to resolve conflict" },
  { word: "Neutrality", definition: "not taking sides in conflict" },
  { word: "Reconciliation", definition: "restoring friendly relations" },
  { word: "Sanctions", definition: "penalties to punish countries" },
  { word: "Sovereignty", definition: "authority over a state" },
  { word: "Terrorism", definition: "using violence to achieve political goals" },
  { word: "Treaty", definition: "formal agreement between states" },
  { word: "Ultimatum", definition: "final demand" },
  { word: "Unilateral", definition: "action by one country alone" },
  { word: "War crimes", definition: "illegal acts during war" },
  { word: "Xenophobia", definition: "fear or hatred of foreigners" },
  { word: "Annexation", definition: "adding territory to a country" },
  { word: "Ballistic", definition: "related to projectiles' motion" },
  { word: "Ceasefire", definition: "end of fighting" },
  { word: "Coalition", definition: "union of groups" },
  { word: "Conscription", definition: "compulsory military service" },
  { word: "Diaspora", definition: "dispersion of people from homeland" },
  { word: "Demilitarized", definition: "area free from military forces" },
  { word: "Diplomat", definition: "official representing a country" },
  { word: "Embassies", definition: "diplomatic offices" },
  { word: "Extradition", definition: "legal surrender of suspects" },
  { word: "Genocide", definition: "targeted mass killing" },
  { word: "Hostilities", definition: "acts of war" },
  { word: "Insurgent", definition: "rebel fighter" },
  { word: "Militarization", definition: "arming for war" },
  { word: "Multilateral", definition: "involving multiple parties" },
  { word: "Nonproliferation", definition: "limiting spread of weapons" },
  { word: "Occupation", definition: "control by military forces" },
  { word: "Partition", definition: "division into parts" },
  { word: "Proxy war", definition: "conflict fought through substitutes" },
  { word: "Realpolitik", definition: "pragmatic politics" },
  { word: "Regime", definition: "government system" },
  { word: "Acquittal", definition: "a judgment that a person is not guilty" },
  { word: "Affidavit", definition: "a written statement confirmed by oath" },
  { word: "Alibi", definition: "evidence that a person was elsewhere during a crime" },
  { word: "Arraignment", definition: "formal reading of charges in court" },
  { word: "Bailiff", definition: "officer who keeps order in court" },
  { word: "Barrister", definition: "lawyer who represents clients in higher courts" },
  { word: "Bench warrant", definition: "order for arrest issued by judge" },
  { word: "Brief", definition: "written summary of a case" },
  { word: "Burglary", definition: "illegal entry to commit crime" },
  { word: "Capital punishment", definition: "death penalty" },
  { word: "Case law", definition: "law established by judicial decisions" },
  { word: "Certified copy", definition: "official duplicate of a document" },
  { word: "Charge sheet", definition: "document specifying crimes accused of" },
  { word: "Circumstantial", definition: "based on inferred evidence" },
  { word: "Class action", definition: "lawsuit filed on behalf of a group" },
  { word: "Codicil", definition: "amendment to a will" },
  { word: "Complainant", definition: "person who makes a legal complaint" },
  { word: "Confession", definition: "admission of guilt" },
  { word: "Contempt", definition: "disobedience to court orders" },
  { word: "Contraband", definition: "illegal goods" },
  { word: "Conviction", definition: "finding of guilt" },
  { word: "Corpus delicti", definition: "facts proving a crime occurred" },
  { word: "Cross-examination", definition: "questioning of a witness by opposing party" },
  { word: "Custody", definition: "detention by law enforcement" },
  { word: "Defendant", definition: "person accused or sued" },
  { word: "Deposition", definition: "sworn out-of-court testimony" },
  { word: "Docket", definition: "court calendar or record of cases" },
  { word: "Due process", definition: "legal requirement of fair treatment" },
  { word: "Embezzlement", definition: "theft of property entrusted to someone" },
  { word: "Entrapment", definition: "inducing a person to commit a crime" },
  { word: "Exculpatory", definition: "evidence clearing someone from guilt" },
  { word: "Exclusionary rule", definition: "prohibits illegally obtained evidence" },
  { word: "Felony", definition: "a serious crime" },
  { word: "Forensic", definition: "relating to scientific crime investigation" },
  { word: "Fraud", definition: "intentional deception for gain" },
  { word: "Grand jury", definition: "group deciding whether enough evidence for trial" },
  { word: "Habeas corpus", definition: "legal order requiring prisoner brought to court" },
  { word: "Harassment", definition: "aggressive pressure or intimidation" },
  { word: "Hearsay", definition: "secondhand evidence" },
  { word: "Indictment", definition: "formal charge initiating trial" },
  { word: "Injunction", definition: "court order to act or stop acting" },
  { word: "Intimidation", definition: "threatening behavior to influence" },
  { word: "Jurisdiction", definition: "authority of a court to hear cases" },
  { word: "Jury", definition: "group deciding case verdict" },
  { word: "Lawsuit", definition: "legal case between parties" },
  { word: "Legal precedent", definition: "earlier court decision guiding later cases" },
  { word: "Litigant", definition: "party involved in a lawsuit" },
  { word: "Misdemeanor", definition: "minor crime" },
  { word: "Motion", definition: "formal request to court" },
  { word: "Negligence", definition: "failure to take proper care" },
  { word: "Oath", definition: "solemn promise to tell truth" },
  { word: "Objection", definition: "formal protest during trial" },
  { word: "Parole", definition: "release of prisoner with conditions" },
  { word: "Perjury", definition: "lying under oath" },
  { word: "Plaintiff", definition: "person who files a lawsuit" },
  { word: "Plea bargain", definition: "agreement to plead guilty for reduced sentence" },
  { word: "Power of attorney", definition: "legal authority to act for another" },
  { word: "Precedent", definition: "legal decision influencing future cases" },
  { word: "Preliminary hearing", definition: "initial court proceeding" },
  { word: "Probation", definition: "supervised release instead of prison" },
  { word: "Prosecution", definition: "bringing a case against someone in court" },
  { word: "Public defender", definition: "lawyer provided for defendants who can't afford one" },
  { word: "Quash", definition: "reject or void legally" },
  { word: "Rebuttal", definition: "contradicting evidence" },
  { word: "Recidivism", definition: "relapse into criminal behavior" },
  { word: "Remedy", definition: "legal means to enforce a right" },
  { word: "Retainer", definition: "fee paid to a lawyer" },
  { word: "Restitution", definition: "compensation for loss or injury" },
  { word: "Sentence", definition: "punishment assigned by court" },
  { word: "Solicit", definition: "to ask for something, often illegally" },
  { word: "Subpoena", definition: "order to appear in court" },
  { word: "Testimony", definition: "evidence given by witness" },
  { word: "Testator", definition: "person who makes a will" },
  { word: "Tort", definition: "civil wrong causing injury" },
  { word: "Transcript", definition: "written record of court proceedings" },
  { word: "Trespass", definition: "unlawful entry onto property" },
  { word: "Trustee", definition: "person managing property for another" },
  { word: "Verdict", definition: "decision in a trial" },
  { word: "Voir dire", definition: "jury selection process" },
  { word: "Warrant", definition: "court order authorizing arrest or search" },
  { word: "Witness", definition: "person who sees or can testify" },
  { word: "Writ", definition: "formal legal order" },
  { word: "Advocacy", definition: "support for a cause or proposal" },
  { word: "Allege", definition: "claim without proof" },
  { word: "Bail", definition: "temporary release awaiting trial" },
  { word: "Burden of proof", definition: "obligation to prove allegations" },
  { word: "Collateral", definition: "security for a loan" },
  { word: "Contingency", definition: "dependent on chance" },
  { word: "Damages", definition: "monetary compensation for harm" },
  { word: "Deposition", definition: "out-of-court sworn testimony" },
  { word: "Diversion", definition: "alternative to prosecution" },
  { word: "Extradition", definition: "surrender of accused between jurisdictions" },
  { word: "Felon", definition: "person convicted of serious crime" },
  { word: "Forfeit", definition: "lose as penalty" },
  { word: "Harangue", definition: "lengthy, aggressive speech" },
  { word: "Impeachment", definition: "formal charge against official" },
  { word: "Indigent", definition: "poor person unable to afford lawyer" },
  { word: "Infraction", definition: "minor violation" },
  { word: "Injunction", definition: "court order to prevent action" },
  { word: "Jurisprudence", definition: "theory or philosophy of law" },
  { word: "Larceny", definition: "theft of personal property" },
  { word: "Litigate", definition: "to take legal action" },
  { word: "Mandate", definition: "official order" },
  { word: "Negotiate", definition: "discuss to reach agreement" },
  { word: "Parole", definition: "conditional release from prison" },
  { word: "Perpetrator", definition: "person who commits a crime" },
  { word: "Plea", definition: "formal statement by defendant" },
  { word: "Pro bono", definition: "legal work for free" },
  { word: "Recuse", definition: "to disqualify oneself from case" },
  { word: "Remand", definition: "send back to custody or lower court" },
  { word: "Sequester", definition: "isolate jury during trial" },
  { word: "Statute", definition: "written law passed by legislature" },
  { word: "Summons", definition: "order to appear in court" },
  { word: "Acquisition", definition: "act of obtaining or gaining possession" },
  { word: "Amortization", definition: "gradual repayment of a debt or cost over time" },
  { word: "Annuity", definition: "fixed sum of money paid regularly" },
  { word: "Arbitrage", definition: "simultaneous buying and selling for profit" },
  { word: "Asset", definition: "resource with economic value owned by a business" },
  { word: "Bankruptcy", definition: "legal declaration of inability to pay debts" },
  { word: "Bear market", definition: "market where prices fall steadily" },
  { word: "Benchmark", definition: "standard for comparison" },
  { word: "Bilateral", definition: "involving two parties or countries" },
  { word: "Bond", definition: "debt security issued by an entity" },
  { word: "Bull market", definition: "market with rising prices" },
  { word: "Capital", definition: "wealth used for investment" },
  { word: "Capitalism", definition: "economic system with private ownership" },
  { word: "Collateral", definition: "asset used to secure a loan" },
  { word: "Commodity", definition: "basic good used in commerce" },
  { word: "Consolidation", definition: "process of combining assets or companies" },
  { word: "Credit", definition: "ability to borrow money" },
  { word: "Depreciation", definition: "reduction in value of an asset over time" },
  { word: "Deregulation", definition: "removal of government controls" },
  { word: "Dividend", definition: "portion of company profits paid to shareholders" },
  { word: "Economies of scale", definition: "cost advantages from increased production" },
  { word: "Equity", definition: "ownership interest in a company" },
  { word: "Escrow", definition: "holding property or money by a third party" },
  { word: "Fiduciary", definition: "person entrusted with managing assets" },
  { word: "Financing", definition: "providing funds for business activities" },
  { word: "Fiscal policy", definition: "government adjustments to spending and taxation" },
  { word: "Foreclosure", definition: "legal process to take ownership due to loan default" },
  { word: "Franchise", definition: "authorization to operate a business under a company's name" },
  { word: "Gross domestic product (GDP)", definition: "total value of goods produced domestically" },
  { word: "Hedge fund", definition: "investment fund using advanced strategies" },
  { word: "Inflation", definition: "general increase in prices" },
  { word: "Insolvency", definition: "inability to pay debts as they fall due" },
  { word: "Interest rate", definition: "percentage charged on borrowed money" },
  { word: "Investment", definition: "allocation of money expecting future return" },
  { word: "Joint venture", definition: "business arrangement between two entities" },
  { word: "Leverage", definition: "using borrowed capital for investment" },
  { word: "Liability", definition: "legal responsibility for debts or actions" },
  { word: "Liquidity", definition: "availability of liquid assets" },
  { word: "Merger", definition: "combination of two companies into one" },
  { word: "Monetization", definition: "process of converting assets into cash" },
  { word: "Monopolize", definition: "control exclusively" },
  { word: "Mortgage", definition: "loan secured by real estate" },
  { word: "Mutual fund", definition: "investment fund pooling money from investors" },
  { word: "Oligopoly", definition: "market dominated by few sellers" },
  { word: "Overhead", definition: "ongoing business expenses" },
  { word: "Portfolio", definition: "collection of investments" },
  { word: "Privatization", definition: "transfer of business from public to private ownership" },
  { word: "Profit margin", definition: "percentage of revenue remaining after expenses" },
  { word: "Prospectus", definition: "document describing a business offering to investors" },
  { word: "Quotation", definition: "latest price in a market" },
  { word: "Recession", definition: "period of economic decline" },
  { word: "Redundancy", definition: "elimination of jobs or assets" },
  { word: "Regulation", definition: "government rules controlling business" },
  { word: "Return on investment (ROI)", definition: "gain from investment relative to cost" },
  { word: "Revenue", definition: "income from business activities" },
  { word: "Securities", definition: "financial instruments representing ownership or debt" },
  { word: "Shareholder", definition: "owner of shares in a company" },
  { word: "Short selling", definition: "selling borrowed securities expecting price drop" },
  { word: "Solvency", definition: "ability to meet long-term debts" },
  { word: "Stakeholder", definition: "person with interest in a company" },
  { word: "Stock exchange", definition: "marketplace for buying and selling stocks" },
  { word: "Subsidiary", definition: "company controlled by another company" },
  { word: "Tariff", definition: "tax on imported goods" },
  { word: "Taxation", definition: "process of imposing taxes" },
  { word: "Trade deficit", definition: "when imports exceed exports" },
  { word: "Trademark", definition: "legally protected brand identifier" },
  { word: "Turnover", definition: "total sales or revenue" },
  { word: "Underwriting", definition: "assuming financial risk for a fee" },
  { word: "Venture capital", definition: "funding for startups with high growth potential" },
  { word: "Volatility", definition: "degree of variation in market prices" },
  { word: "Yield", definition: "income return on investment" },
  { word: "Acquisition cost", definition: "expense to acquire an asset or company" },
  { word: "Aggregate demand", definition: "total demand for goods and services" },
  { word: "Amortize", definition: "gradually pay off debt" },
  { word: "Arbitrageur", definition: "person engaging in arbitrage" },
  { word: "Balance sheet", definition: "financial statement of assets and liabilities" },
  { word: "Capital expenditure", definition: "funds used to acquire fixed assets" },
  { word: "Cash flow", definition: "amount of cash generated or spent" },
  { word: "Collusion", definition: "secret agreement to deceive or defraud" },
  { word: "Consumer price index (CPI)", definition: "measure of inflation based on price changes" },
  { word: "Derivative", definition: "financial contract deriving value from underlying asset" },
  { word: "Divestiture", definition: "selling off business assets" },
  { word: "Econometrics", definition: "application of statistical methods to economics" },
  { word: "Endowment", definition: "funds or property given to an institution" },
  { word: "Fiscal year", definition: "annual accounting period" },
  { word: "Futures contract", definition: "agreement to buy/sell assets at predetermined price in future" },
  { word: "Hedge", definition: "investment to reduce risk" },
  { word: "Impairment", definition: "reduction in asset's recoverable value" },
  { word: "Index fund", definition: "investment fund tracking a market index" },
  { word: "Insolvent", definition: "unable to pay debts" },
  { word: "Intellectual property", definition: "legal rights to inventions and creations" },
  { word: "Investment banking", definition: "banking services for capital raising and mergers" },
  { word: "Leveraged buyout", definition: "purchase using significant borrowed funds" },
  { word: "Liquidity ratio", definition: "measure of ability to meet short-term obligations" },
  { word: "Market capitalization", definition: "total market value of company's shares" },
  { word: "Microeconomics", definition: "study of individual economic behavior" },
  { word: "Mortgagor", definition: "borrower in a mortgage agreement" },
  { word: "Mutual fund", definition: "pooled investments managed by professionals" },
  { word: "Nominal value", definition: "face value of a security" },
  { word: "Over-the-counter (OTC)", definition: "trading done directly between parties" },
  { word: "Portfolio management", definition: "process of managing investment blend" },
  { word: "Price-earnings ratio", definition: "valuation metric of stock price relative to earnings" },
  { word: "Quantitative easing", definition: "monetary policy to increase money supply" },
  { word: "Quorum", definition: "minimum number required for decisions" },
  { word: "Return on equity (ROE)", definition: "profitability measure for shareholders" },
  { word: "Securitization", definition: "process of pooling financial assets for sale" },
  { word: "Small-cap", definition: "company with small market capitalization" },
  { word: "Tangible assets", definition: "physical assets like equipment or property" },
  { word: "Treasury bonds", definition: "government debt securities with long maturity" }
];



